class Data_create():
    valid_name ="Jazi"
    valid_company="Wow"
    valid_adress="Temanggung"
    valid_city="Temanggung"
    valid_phone="089652563654"
    valid_email="jazilaatiya@gmail.com"
    invalid_phone="089652563654ee"
    invalid_email="jazila"
    empty_name =""
    empty_company=""
    empty_adress=""
    empty_city=""
    empty_phone=""
    empty_email=""